module.exports = [
  { id: '01', name: 'IGO Engineering', head: 'Head of Engineering', focus: 'Farm infrastructure, civil & structural works', icon: '🏗️' },
  { id: '02', name: 'IGO Agri Operations', head: 'Head of Agri Operations', focus: 'Field execution, crop management, farm productivity', icon: '🌾' },
  { id: '03', name: 'IGO Business Development', head: 'Head of Business Development', focus: 'New clients, partnerships, revenue growth', icon: '📊' },
  { id: '04', name: 'IGO Purchase', head: 'Head of Purchase', focus: 'Procurement, vendor management, cost control', icon: '🛒' },
  { id: '05', name: 'IGO Labour Vendor Sourcing', head: 'Head of Labour Vendor Sourcing', focus: 'Labour supply chain, contractor management', icon: '👷' },
  { id: '06', name: 'IGO Human Resources', head: 'Head of Human Resources', focus: 'Talent acquisition, employee welfare, culture', icon: '👥' },
  { id: '07', name: 'IGO Lease & Buying Sourcing', head: 'Head of Lease & Buying Sourcing', focus: 'Land leasing, property acquisition', icon: '🏡' },
  { id: '08', name: 'IGO Marketing', head: 'Head of Marketing', focus: 'Brand building, campaigns, digital presence', icon: '📣' },
  { id: '09', name: 'IGO CRM', head: 'Head of CRM', focus: 'Customer relationships, retention, satisfaction', icon: '🤝' },
  { id: '10', name: 'IGO Data Analytics & Legal', head: 'Head of Data Analytics & Legal', focus: 'Data intelligence, compliance, legal affairs', icon: '⚖️' },
  { id: '11', name: 'IGO Research & Development', head: 'Head of R&D', focus: 'Agri innovation, new techniques, technology trials', icon: '🔬' },
  { id: '12', name: 'IGO Accounts, Audit & Compliance', head: 'Head of Accounts', focus: 'Financial reporting, audits, regulatory compliance', icon: '📋' },
  { id: '13', name: 'IGO IT & Artificial Intelligence', head: 'Head of IT & AI', focus: 'Tech infrastructure, AI tools, digital systems', icon: '🤖' },
  { id: '14', name: 'IGO Administration', head: 'Head of Administration', focus: 'Office management, logistics, support services', icon: '🏢' },
  { id: '15', name: 'IGO Site Visit', head: 'Head of Site Visit', focus: 'Field inspections, site assessments, quality checks', icon: '🔍' },
  { id: '16', name: 'IGO Farm Manager Welfare', head: 'Head of Farm Manager Welfare', focus: 'Farm manager support, welfare, development', icon: '❤️' },
  { id: '17', name: 'IGO Management Operations Team', head: 'Head of MOT', focus: 'Cross-functional coordination, operational excellence', icon: '⚙️' },
  { id: '18', name: 'IGO Networking & Associations', head: 'Head of Networking & Associations', focus: 'Industry ties, government relations, strategic alliances', icon: '🌐' },
];
